install.packages('dplyr')
install.packages('ggplot2')
install.packages('ggdendro')
install.packages('pheatmap')
install.packages('cowplot')
install.packages('knitr')
install.packages('rmarkdown')
install.packages('DescTools')
install.packages('caret')
install.packages('glmnet')
install.packages('nnet')
install.packages('adabag')

# For interactive app
# install.packages("shiny")
# install.packages("shinyjs")
# install.packages("reshape2")
# install.packages("torchaudio")
# install.packages("base64enc")
